// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/worky-conversations/Current.tsx": () => import("../components/mockups/worky-conversations/Current.tsx"),
  "./components/mockups/worky-conversations/WhatsAppInbox.tsx": () => import("../components/mockups/worky-conversations/WhatsAppInbox.tsx"),
  "./components/mockups/worky-discovery/Current.tsx": () => import("../components/mockups/worky-discovery/Current.tsx"),
  "./components/mockups/worky-discovery/PremiumDiscovery.tsx": () => import("../components/mockups/worky-discovery/PremiumDiscovery.tsx")
};
